---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pv-gc
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-gc
rules:
  - apiGroups: [ "" ]
    resources: [ "persistentvolumes"]
    verbs: [ "*" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pv-gc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pv-gc
subjects:
  - kind: ServiceAccount
    name: pv-gc
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-gc
  namespace: default
  labels:
    app: pv-gc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-gc
  template:
    metadata:
      labels:
        app: pv-gc
    spec:
      serviceAccountName: pv-gc
      containers:
        - name: controller
          image: pv-gc:0.0.1
          command:
          - "/controller"
          - "--bind-address=0.0.0.0:9090"
          - "--reconcile-time=1m"
          - "--wait-before-delete-time=5m"
          ports:
          - containerPort: 9090
